const themeArray = [
  {
    theme: "art",
    name: "Art",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/art.png",
  },
  {
    theme: "ajs",
    name: "AJS",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/ajs.png",
  },
  {
    theme: "aviation",
    name: "Aviation",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/aviation.png",
  },
  {
    theme: "business",
    name: "Business",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/business.png",
  },
  {
    theme: "cad",
    name: "CAD",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/cad.png",
  },
  {
    theme: "cards",
    name: "Cards",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/cards.png",
  },
  {
    theme: "cda",
    name: "CDA",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/cda.png",
  },
  {
    theme: "communication",
    name: "Communication",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/communication.png",
  },
  {
    theme: "computer-information-systems",
    name: "Computer Information Systems",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/cis.png",
  },
  {
    theme: "culinary",
    name: "Culinary",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/culinary.png",
  },
  {
    theme: "dental",
    name: "Dental",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/dental.png",
  },
  {
    theme: "ece",
    name: "Early Childhood Education",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/ece.png",
  },
  {
    theme: "fashion",
    name: "Fashion",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/fashion.png",
  },
  {
    theme: "fitness",
    name: "Fitness",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/fitness.png",
  },
  {
    theme: "geography",
    name: "Geography",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/geography.png",
  },
  {
    theme: "geology",
    name: "Geology",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/geology.png",
  },
  {
    theme: "health-it",
    name: "Health IT",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/health-it.png",
  },
  {
    theme: "history",
    name: "History",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/history.png",
  },
  {
    theme: "hrs",
    name: "Human Resources",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/hrs.png",
  },
  {
    theme: "journalism",
    name: "Journalism",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/journalism.png",
  },
  {
    theme: "lang",
    name: "Language",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/language.png",
  },
  {
    theme: "lgm",
    name: "Logistics Management",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/lgm.png",
  },
  {
    theme: "machine",
    name: "Machinery",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/mac.png",
  },
  {
    theme: "math",
    name: "Math",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/math.png",
  },
  {
    theme: "minimalist",
    name: "Minimalist",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/minimalist.png",
  },
  {
    theme: "music",
    name: "Music",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/music.png",
  },
  {
    theme: "philosophy",
    name: "Philosophy",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/phi.png",
  },
  {
    theme: "resort",
    name: "Resort",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/resort.png",
  },
  {
    theme: "soc",
    name: "SOC",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/soc.png",
  },
  {
    theme: "university",
    name: "University",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/university.png",
  },
  {
    theme: "vet",
    name: "Veterinarian",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/vet.png",
  },
  {
    theme: "welding",
    name: "Welding",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/welding.png",
  },
  {
    theme: "writing",
    name: "Writing",
    description: "This theme uses a gradient in the background and adds frames to images.",
    image: "/images/themes/writing.png",
  }
  // Add more themes to the array
];

export default themeArray;